NVIDIA: SAUCE: virtinst: Fix CCA launchSecurity property name mappings
The second argument to add_arg() should be the Python property name,
not the CLI argument name. This was causing errors when trying to use
CCA-specific properties.

Before this fix:
  --launchSecurity type=cca,measurementLog=on
  ERROR: obj=<DomainLaunchSecurity> does not have member=measurement-log

Signed-off-by: Ian May <ianm@nvidia.com>